FROM justmoon/wix

USER root

# Install OS dependencies
RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        make \
        git \
        software-properties-common

RUN add-apt-repository -y ppa:deadsnakes/ppa

RUN set -ex \
    && apt-get install -y --no-install-recommends \
        libgirepository1.0-dev \
        libcairo2-dev \
        gir1.2-webkit2-3.0 \
        python3.5 \
        python3.5-dev \
        python3.5-venv \
        libpython3-dev \
        python3-pip \
        python3-gi \
        python3-setuptools

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash

RUN set -ex \
    && apt-get install -y --no-install-recommends \
        nodejs

RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install yarn
RUN npm install -g npm
RUN npm install -g grunt-cli && \
    echo '{ "allow_root": true }' > /root/.bowerrc

RUN pip3 install --upgrade pip
#RUN python3 -m venv /home/wix/venv

COPY . /dativetop

ENV GIT_DIR=/dativetop/src/dative

WORKDIR /dativetop/src/dative/
RUN yarn
WORKDIR /dativetop/src/dative/test/
RUN yarn

WORKDIR /dativetop/src/dative/
CMD grunt build

WORKDIR /dativetop/
#RUN pip3 install beeware
#RUN pip3 install -r src/old/requirements/test.txt
#RUN pip3 install -e src/old/

#ADD example.wxs /home/wix/example.wxs
#RUN wine candle.exe /home/wix/example.wxs
#RUN wine light.exe /home/wix/example.wixobj

