version: 2.1

jobs:

  test_dtserver:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run:
          name: "Install DTServer dependencies"
          command: "pip install -e src/dativetop/server[testing]"
      - run:
          name: "Build the DTServer SQLite database"
          command: "initialize_dtserver_db src/dativetop/server/config.ini"
      - run:
          name: "Run the DTServer tests"
          command: "pytest src/dativetop/server/tests"

  build-dativetop-gui:
    docker:
      - image: cimg/base:2020.10
    environment:
      IMAGE_NAME: dativebase/dativetop-gui
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: cd docker build -t $IMAGE_NAME:latest .

workflows:
  version: 2
  test:
    jobs:
      - test_dtserver
